import type {Metadata} from 'next'
import {Open_Sans} from 'next/font/google'
import NProgressProvider from '../components/NProgressProvider'
import Navbar from '../components/Navbar'
import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'

const fontPrimary = Open_Sans({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body className={fontPrimary.className}>
        <NProgressProvider>
          <Navbar />
          {children}
        </NProgressProvider>
      </body>
    </html>
  )
}
